blank_issues_enabled: false
contact_links:
  - name: Link na discord
    url: https://discord.ssps.cajthaml.eu/
    about: Zde se můžete před odesláním zeptat na další věci.
  - name: Link na webový portál
    url: https://ssps.cajthaml.eu
    about: Informace o učení a jednotlivých předmětech.
  - name: Link na status služeb 
    url: https://status.cajthaml.eu
    about: Stránka obsahující status služeb, které souvisí s portálem.
